name: apidocs
on:
- push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install requirements for documentation generation
      run: |
        python -m pip install -U sphinx
        python -m pip install sphinx_bootstrap_theme

    - name: Generate html files for github using Sphinx
      run: |

        # Run shpinx build
        cd docs
        ls
        sphinx-build -b html .\build_files\ .\
        